/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, CameraControls } from '@react-three/drei'
import { button, useControls } from 'leva'

export function MainRobo(props) {
  const { nodes, materials } = useGLTF('/models/main_robo.gltf')
  const camera = useRef()



  return (
    <group {...props} dispose={null}>
        {/* <CameraControls ref={camera}/> */}  
        <group scale={0.03} rotation={[0,-Math.PI/2 + (20 * Math.PI/180),0]} position={[0,-.1,0]}>
          <group name="Scene_1" userData={{ name: 'Scene 1' }}>
            {/* <PerspectiveCamera
              name="Camera"
              makeDefault={false}
              far={100000}
              near={70}
              fov={45}
              position={[189.475, 6.014, 72.338]}
              rotation={[-0.17, 1.122, 0.154]}
              userData={{ name: 'Camera' }}
            /> */}
            <group name="Light" position={[59.064, 150, 96.782]} userData={{ name: 'Light' }}>
              <directionalLight
                name="Directional_Light_3"
                intensity={0.436}
                decay={2}
                color="#f8d6d0"
                rotation={[-1.266, -0.295, -1.48]}
                userData={{ name: 'Directional Light 3' }}>
                <group position={[0, 0, -1]} />
              </directionalLight>
              <directionalLight
                name="Directional_Light_2"
                intensity={1.769}
                decay={2}
                color="#bdddf6"
                rotation={[-2.756, 0.519, -0.686]}
                userData={{ name: 'Directional Light 2' }}>
                <group position={[0, 0, -1]} />
              </directionalLight>
              <directionalLight
                name="Directional_Light"
                intensity={0.29}
                decay={2}
                rotation={[-0.398, 0.51, 0.711]}
                userData={{ name: 'Directional Light' }}>
                <group position={[0, 0, -1]} />
              </directionalLight>
            </group>
            <group
              name="RoBOT_(Duplicate)"
              position={[0, -2.405, 0]}
              scale={98.043}
              userData={{ name: 'RoBOT_(Duplicate)' }}>
              <group
                name="Head"
                position={[0, -0.002, 0]}
                rotation={[0, -0.374, -0.03]}
                scale={0.01}
                userData={{ name: 'Head' }}>
                <group
                  name="Head_Elements"
                  position={[-0.084, 25.17, 0]}
                  rotation={[0, 0, -0.122]}
                  scale={98.043}
                  userData={{ name: 'Head Elements' }}>
                  <group
                    name="New_Headphone"
                    position={[0.001, -0.257, 0]}
                    userData={{ name: 'New Headphone' }}>
                    <mesh
                      name="Cylinder"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder.geometry}
                      material={nodes.Cylinder.material}
                      userData={{ name: 'Cylinder' }}
                    />
                    <mesh
                      name="Ears"
                      castShadow
                      receiveShadow
                      geometry={nodes.Ears.geometry}
                      material={nodes.Ears.material}
                      userData={{ name: 'Ears' }}
                    />
                    <mesh
                      name="Cylinder002"
                      castShadow
                      receiveShadow
                      geometry={nodes.Cylinder002.geometry}
                      material={nodes.Cylinder002.material}
                      userData={{ name: 'Cylinder002' }}
                    />
                  </group>
                  <group
                    name="Mouth_Move_2"
                    position={[0.202, -0.084, 0]}
                    scale={[0.01, 0.012, 0.01]}
                    userData={{ name: 'Mouth Move 2' }}>
                    <mesh
                      name="Mouth"
                      castShadow
                      receiveShadow
                      geometry={nodes.Mouth.geometry}
                      material={nodes.Mouth.material}
                      position={[-19.679, -16.701, 0]}
                      scale={98.043}
                      userData={{ name: 'Mouth' }}
                    />
                  </group>
                  <group
                    name="Eyes_Move"
                    position={[0.202, -0.019, 0]}
                    scale={[0.01, 0.009, 0.01]}
                    userData={{ name: 'Eyes Move' }}>
                    <mesh
                      name="Eyes"
                      castShadow
                      receiveShadow
                      geometry={nodes.Eyes.geometry}
                      material={nodes.Eyes.material}
                      position={[-19.679, -23.054, 0]}
                      scale={98.043}
                      userData={{ name: 'Eyes' }}
                    />
                  </group>
                  <mesh
                    name="Head_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Head_1.geometry}
                    material={nodes.Head_1.material}
                    position={[0.001, -0.255, 0]}
                    userData={{ name: 'Head_1' }}
                  />
                  <mesh
                    name="Head_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Head_2.geometry}
                    material={nodes.Head_2.material}
                    position={[0.001, -0.255, 0]}
                    userData={{ name: 'Head_2' }}
                  />
                </group>
              </group>
              <group
                name="Body_Elements"
                position={[0.012, -0.223, 0]}
                userData={{ name: 'Body Elements' }}>
                <mesh
                  name="Neck"
                  castShadow
                  receiveShadow
                  geometry={nodes.Neck.geometry}
                  material={nodes.Neck.material}
                  position={[-0.012, 0.223, 0]}
                  userData={{ name: 'Neck' }}
                />
                <mesh
                  name="Body"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body.geometry}
                  material={nodes.Body.material}
                  position={[-0.012, 0.223, 0]}
                  userData={{ name: 'Body' }}
                />
                <mesh
                  name="Body_Circle_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body_Circle_1.geometry}
                  material={nodes.Body_Circle_1.material}
                  position={[-0.012, 0.223, 0]}
                  userData={{ name: 'Body Circle_1' }}
                />
                <mesh
                  name="Body_Circle_2"
                  castShadow
                  receiveShadow
                  geometry={nodes.Body_Circle_2.geometry}
                  material={nodes.Body_Circle_2.material}
                  position={[-0.012, 0.223, 0]}
                  userData={{ name: 'Body Circle_2' }}
                />
              </group>
              <group name="ARM_R" position={[0.038, -0.254, 0.254]} userData={{ name: 'ARM_R' }}>
                <group
                  name="NULL_for_Animation_arm"
                  position={[-0.016, 0.17, -0.042]}
                //   rotation={[1.935, -1.484, 3.022]}
                  userData={{ name: 'NULL for Animation arm' }}>
                  <group
                    name="Hand_Down"
                    position={[0, -0.156, 0.052]}
                    rotation={[-0.058, -0.008, 0.101]}
                    scale={0.01}
                    userData={{ name: 'Hand Down' }}>
                    <group
                      name="Group"
                      position={[1.388, -13.646, 1.559]}
                      scale={98.043}
                      userData={{ name: 'Group' }}>
                      <mesh
                        name="Arm_R"
                        castShadow
                        receiveShadow
                        geometry={nodes.Arm_R.geometry}
                        material={nodes.Arm_R.material}
                        position={[-0.01, 0.273, -0.071]}
                        userData={{ name: 'Arm_R' }}
                      />
                      <mesh
                        name="HAND_R"
                        castShadow
                        receiveShadow
                        geometry={nodes.HAND_R.geometry}
                        material={nodes.HAND_R.material}
                        position={[-0.01, 0.074, 0.014]}
                        rotation={[Math.PI, -1.571, 0]}
                        userData={{ name: 'HAND_R' }}
                      />
                    </group>
                  </group>
                  <mesh
                    name="Forearm_R"
                    castShadow
                    receiveShadow
                    geometry={nodes.Forearm_R.geometry}
                    material={nodes.Forearm_R.material}
                    position={[-0.016, 0.058, -0.212]}
                    rotation={[0.035, 0, 0]}
                    scale={[1, 0.8, 1]}
                    userData={{ name: 'Forearm_R' }}
                  />
                </group>
                <mesh
                  name="Shoulder_R"
                  castShadow
                  receiveShadow
                  geometry={nodes.Shoulder_R.geometry}
                  material={nodes.Shoulder_R.material}
                  position={[-0.032, 0.26, -0.254]}
                  userData={{ name: 'Shoulder_R' }}
                />
              </group>
              <group name="ARM_L" position={[0.038, -0.254, -0.254]} userData={{ name: 'ARM_L' }}>
                <mesh
                  name="Hand_L"
                  castShadow
                  receiveShadow
                  geometry={nodes.Hand_L.geometry}
                  material={nodes.Hand_L.material}
                  position={[-0.032, 0.223, 0.286]}
                  rotation={[0, 0, -0.004]}
                  scale={[0.773, 0.865, 0.892]}
                  userData={{ name: 'Hand_L' }}
                />
                <mesh
                  name="Arm_L"
                  castShadow
                  receiveShadow
                  geometry={nodes.Arm_L.geometry}
                  material={nodes.Arm_L.material}
                  position={[-0.038, 0.254, 0.254]}
                  userData={{ name: 'Arm_L' }}
                />
                <mesh
                  name="Forearm_L"
                  castShadow
                  receiveShadow
                  geometry={nodes.Forearm_L.geometry}
                  material={nodes.Forearm_L.material}
                  position={[-0.038, 0.254, 0.254]}
                  userData={{ name: 'Forearm_L' }}
                />
                <mesh
                  name="Shoulder_L"
                  castShadow
                  receiveShadow
                  geometry={nodes.Shoulder_L.geometry}
                  material={nodes.Shoulder_L.material}
                  position={[-0.038, 0.254, 0.254]}
                  userData={{ name: 'Shoulder_L' }}
                />
              </group>
            </group>
            <PerspectiveCamera
              makeDefault={false}
              far={100000}
              near={70}
              fov={45}
              position={[190.507, 6.243, 52.754]}
              rotation={[-0.051, 1.175, 0.047]}
            />
            <group
              name="Default_Ambient_Light"
              position={[0, 1, 0]}
              userData={{ name: 'Default Ambient Light' }}
            />
          </group>
        </group>
    </group>
  )
}

useGLTF.preload('/models/main_robo.gltf')
